name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    container: node:16
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn --frozen-lockfile
      - run: yarn lint

  test:
    strategy:
      matrix:
        node-version: [16, 18]
    runs-on: ubuntu-20.04
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"
      - run: yarn --frozen-lockfile
      - run: yarn build && yarn test